from tkinter import*
from PIL import Image,ImageTk
root=Tk()
canvas=Canvas(root,width=735,height=1104)
canvas.pack() 
image_1="travel.png"
image1=Image.open(image_1)
photo1 = ImageTk.PhotoImage(image1)
canvas.create_image(0, 0, image=photo1, anchor=NW)
canvas.create_text(335,270,text="USERNAME",font=("Times New Roman", 14,"bold"))
e_username1=Entry(root,width=30)
canvas.create_window(335,300,window=e_username1)
canvas.create_text(335,350,text="PASSWORD",font=("Montserrat",14,"bold"))
e_password1=Entry(root,width=30)
canvas.create_window(335,390,window=e_password1)
def signup_window():
    second_window = Toplevel(root)
    second_window.title("Sign Up")
    canvas=Canvas(second_window,width=626,height=417)
    canvas.pack(fill='both',expand=True)
    second_window.image_1="signup.png"
    image=Image.open(second_window.image_1)
    second_window.photo = ImageTk.PhotoImage(image)
    canvas.create_image(0, 0, image=second_window.photo, anchor=NW)
    canvas.create_text(195,108,text="USERNAME",font=("Montserrat", 12,"bold"))
    e_username=Entry(second_window,width=30)
    canvas.create_window(250,140,window=e_username)
    canvas.create_text(195,190,text="PASSWORD",font=("Montserrat", 12,"bold"))
    e_username=Entry(second_window,width=30)
    canvas.create_window(250,220,window=e_username)
    create_new=Button(second_window,text="CREATE NEW ACCOUNT",font=("Montserrat", 10,"bold"))
    canvas.create_window(250,270,window=create_new)
signup_btn=Button(root,text="SIGN UP",padx=35,pady=15,font=("Montserrat",14,"bold"),command=signup_window)
canvas.create_window(335,565,window=signup_btn)    
def flight_page():
    flight_window=Toplevel(root)
    flight_window.config(bg="#0076CE")
    flight_window.geometry("600x400")
    label_destination=Label(flight_window,text="DESTINATION",font=("Montserrat", 12,"bold"),bg="#0076CE")
    label_destination.place(x=75,y=75)
    e_desintination=Entry(flight_window,width=30)
    e_desintination.place(x=75,y=95)
    
def login_page():
    login_window=Toplevel(root)
    flight_btn=Button(login_window,text="FLIGHT",font=("Montserrat",14,"bold"),command=flight_page)
    flight_btn.place(x=140,y=60)
    hotel_btn=Button(login_window,text="HOTEL",font=("Montserrat",14,"bold"))
    hotel_btn.place(x=140,y=120)
    car_btn=Button(login_window,text="CAR RENTAL",font=("Montserrat",14,"bold"))
    car_btn.place(x=140,y=180) 
    login_window.geometry("400x300")  
    login_window.config(bg="#64A6A8")
login_btn=Button(root,text="LOGIN",padx=35,pady=15,font=("Montserrat",14,"bold"),command=login_page)
canvas.create_window(335,480,window=login_btn)    
root.mainloop()